import { BrowserModule } from '@angular/platform-browser';
import { NgModule,CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { MatRippleModule } from '@angular/material';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

//MODULOS
import { MetarialModule } from './material.module'
import { AppRoutingModule } from './app-routing.module';

//COMPONENTES
import { AppComponent } from './app.component';
import { HomeComponent } from './components/home/home.component';
import { UbicacionGarantiaComponent, 
         DialogOverviewExampleDialog } from './components/ubicacion-garantia/ubicacion-garantia.component';
import { CategoriasSIBComponent, 
         DailogAgregarCategoriaSIB,
         DailogEliminarCategoriaSIB,
         DailogEditarCategoriaSIB,} from './components/categorias-sib/categorias-sib.component';
import { AgrupacionCreditosComponent } from './components/agrupacion-creditos/agrupacion-creditos.component';
import { AcercamientosComponent, 
         CrearAcercamiento } from './components/acercamientos/acercamientos.component';
import { AlmacenadoraComponent,
         DialogAlma,
         DialogActualizarAlma,
         DialogEliminarAlma } from './components/almacenadora/almacenadora.component';
import { ArchivosLimpiezaComponent, 
         DialogLimpieza,
         DialogEliminarArchivosLimpieza } from './components/archivos-limpieza/archivos-limpieza.component';
import { AseguradorasComponent,
         DialogAseg,
         DialogActualizarAseg,
         DialogEliminarAseg, } from './components/aseguradoras/aseguradoras.component';
import { AsesoresPrestamoComponent,
         CrearAsesoresPrestamos } from './components/asesores-prestamo/asesores-prestamo.component';
import { BancosComponent, 
         CrearBancos } from './components/bancos/bancos.component';
import { CanalesVentaComponent,
         DialogCanal,
         DialogEliminarCanal } from './components/canales-venta/canales-venta.component';
import { CobrosAdicionalesComponent, 
         DialogCobroAdicional} from './components/cobros-adicionales/cobros-adicionales.component';
import { DestinosComponent, 
         DialogDestinos } from './components/destinos/destinos.component';
import { DiasInhabilesComponent, 
         DialogDiaInhabil} from './components/dias-inhabiles/dias-inhabiles.component';
import { EstatusAvaluosComponent, 
         DailogAgregarEstatusAvaluos,
         DailogEditarEstatusAvaluos, 
         DailogEliminarEstatusAvaluos } from './components/estatus-avaluos/estatus-avaluos.component';
import { EstatusGarantiaRealComponent,
         DailogAgregarEstatusGarantiaReal, 
         DailogEditarEstatusGarantiaReal, 
         DailogEliminarEstatusGarantiaReal, } from './components/estatus-garantia-real/estatus-garantia-real.component';
import { FormasDesembolsoComponent, 
         DialogDesembolsoAgregar } from './components/formas-desembolso/formas-desembolso.component';
import { FormasPagoComponent, 
         DialogFormas } from './components/formas-pago/formas-pago.component';
import { FrecuenciasAmortizacionComponent, 
         DialogFrecuenciaAmortizacionAgregar } from './components/frecuencias-amortizacion/frecuencias-amortizacion.component';
import { GarantiasContablesComponent, 
         DialogGa } from './components/garantias-contables/garantias-contables.component';
import { IngenierosValuadoresComponent, 
         DailogAgregarIngenierosValuadores, 
         DailogEditarIngenierosValuadores, 
         DailogEliminarIngenierosValuadores } from './components/ingenieros-valuadores/ingenieros-valuadores.component';
import { InstitucionesCobrosAdicionalesComponent,
         DialogCobrosAgregar, 
         DialogCobrosAgregarCheck } from './components/instituciones-cobros-adicionales/instituciones-cobros-adicionales.component';
import { LugaresInversionComponent,
         DialogAgregarlugaresInversion,
         DialogActualizarlugaresInversion,
         DialogEliminarlugaresInversion } from './components/lugares-inversion/lugares-inversion.component';
import { MotivosAjustesComponent, 
         DialogAgregarMotivoAjuste,
         DialogActualizarMotivoAjuste,
         DialogEliminarMotivoAjuste } from './components/motivos-ajustes/motivos-ajustes.component';
import { MotivosReferenciasClientesComponent } from './components/motivos-referencias-clientes/motivos-referencias-clientes.component';
import { MotivosReservasComponent,
         DailogAgregarMotivosReservasComponent,
         DailogActualizarMotivosReservasComponent,
         DailogEliminarMotivosReservasComponent,
         DailogValorCobroComponent,
         DailogAgregarValorCobroComponent,
         DailogEliminarValorCobroComponent } from './components/motivos-reservas/motivos-reservas.component';
import { NotariosComponent, 
         DialogNotario } from './components/notarios/notarios.component';
import { ParametrizacionNumeroPrestamoComponent, 
         DialogParaPrestamoAgregar } from './components/parametrizacion-numero-prestamo/parametrizacion-numero-prestamo.component';
import { PasosCierreComponent, 
         DialogEventoPasos } from './components/pasos-cierre/pasos-cierre.component';
import { RelacionTransaccionDepositosComponent, 
         DialogRelacion,
         DialogEliminarRelacion } from './components/relacion-transaccion-depositos/relacion-transaccion-depositos.component';
import { TiposCanalesDistribucionComponent, 
         DialogTiposC } from './components/tipos-canales-distribucion/tipos-canales-distribucion.component';
import { TiposDeduccionesComponent, 
         CrearTiposDeducciones } from './components/tipos-deducciones/tipos-deducciones.component';
import { TiposPrestamosComponent, DialogTp } from './components/tipos-prestamos/tipos-prestamos.component';
import { TiposTransaccionesComponent, DialogTr } from './components/tipos-transacciones/tipos-transacciones.component';
import { OrigenFondosComponent, DialogOrigen } from './components/origen-fondos/origen-fondos.component';
import { MediosContactoComponent, 
         DialogContacto,
         DialogEliminarContacto } from './components/medios-contacto/medios-contacto.component';
import { MontosPlazoComponent } from './components/montos-plazo/montos-plazo.component';
import { DefinirCategoriaUsuarioComponent,
         DailogAgregarCategoriaUsuario,
         DailogEliminarCategoriaUsuario,
         DailogEditarCategoriaUsuario } from './components/definir-categoria-usuario/definir-categoria-usuario.component';
import { LimpiezaArchivosComponent, 
         DialogArchivos } from './components/limpieza-archivos/limpieza-archivos.component';
import { DatosGeneralesComponet,
         DialogG,
         DialogE,
         DialogN,
         DialogA   } from './components/datos-generales/datos-generales.component';
import { TiposSubtiposGarantiasRealesComponent, 
         DialogTiposSubtiposAgregar, 
         DialogTiposSubtiposAgregarCheck, 
         TiposSubtiposGarantiasCheckAgregar } from './components/tipos-subtipos-garantias-reales/tipos-subtipos-garantias-reales.component';
import { EstadosPrestamosComponent, 
         DailogAgregarEstadoPrestamo,
         DailogActualizarEstadoPrestamo,
         DailogEliminarEstadoPrestamo,
         DailogSubEstadoPrestamo,
         DailogAgregarSubEstadoPrestamo,
         DailogActualizarSubEstadoPrestamo,
         DailogEliminarSubEstadoPrestamo,
         DailogTrasladoEstadoPrestamo,
         DailogAgregarTrasladoEstadoPrestamo,
         DailogActualizarTrasladoEstadoPrestamo,         
         DailogEliminarTrasladoEstadoPrestamo,
         DailogCriteriosTraslado,
         DailogAgregarCriterio,
         DailogActualizarCriterio,
         DailogEliminarCriterio} from './components/estados-prestamos/estados-prestamos.component';
import { ConsultasComponent, 
         DialogConsultas } from './components/consultas/consultas.component';
import { ProductosComponent, 
         CrearProducto, 
         EditarProducto,
         EliminarProducto } from './components/productos/productos.component';
import { ClasificacionComponent, 
         DialogClasificacion } from './components/clasificacion/clasificacion.component';
import { ParametrosAdicionalesProductosComponent } from './components/parametros-adicionales-producto/parametros-adicionales-productos.component';
import { EventosSolicitudesComponent, 
         DialogEvento } from './components/eventos-solicitudes/eventos-solicitudes.component';
import { DocumentosProductoComponent } from './components/documentos-producto/documentos-producto.component';
import { PorcentajeFinanciamientoComponent } from './components/porcentaje-financiamiento/porcentaje-financiamiento.component';
import { RangoPlazoInteresComponent } from './components/rango-plazo-interes/rango-plazo-interes.component';
import { AsignacionCategoriasComponent,
         DialogEliminarAsignacionCategorias,
         DialogAsignacionCategorias,
         DialogAsignacionCategoriasV,
         DialogAsignacionCategoriasT,
         DialogEliminarAsignacionTipoProducto } from './components/Asignacion-de-Categorias/Asignacion-de-Categorias.component';
import { CopiarParametrosProductosComponent } from './components/Copiar-Parametros-de-Productos/Copiar-parametros-de-Productos.component';
import { Estatuslegalescomponent, 
         dialogEstatusLegales } from './components/estatus-legales/estatus-legales.component';
import { DialogDocumentoProducto } from './components/documentos-producto/documentos-producto.component';
import { dialogCopiarParametros } from './components/Copiar-Parametros-de-Productos/Copiar-parametros-de-Productos.component';
import { SidenavComponent } from './components/sidenav/sidenav.component';
import { EnlaceContabilidadComponent,
         DailogAgregarEnlaceContabilidad, 
         DailogEliminarEnlaceContabilidad, 
         DailogEditarEnlaceContabilidad } from './components/enlace-contabilidad/enlace-contabilidad.component';
import { NivelesContabilizacionComponent,
         DailogAgregarNivelesContabilizacion,
         DailogEliminarNivelesContabilizacion, } from './components/niveles-contabilizacion/niveles-contabilizacion.component';
import { ContenidosContablesComponent,
         DailogAgregarContenidosContables,
         DailogEditarContenidosContables,
         DailogEliminarContenidosContables, } from './components/contenidos-contables/contenidos-contables.component';         

@NgModule({
  declarations: [
    AppComponent,
    HomeComponent,
    AlmacenadoraComponent,
    DialogAlma,
    DialogActualizarAlma,
    DialogEliminarAlma,
    AseguradorasComponent,
    DialogAseg,
    DialogActualizarAseg,
    DialogEliminarAseg,
    AgrupacionCreditosComponent,
    LugaresInversionComponent,
    DialogAgregarlugaresInversion,
    DialogActualizarlugaresInversion,
    DialogEliminarlugaresInversion,
    UbicacionGarantiaComponent,
    OrigenFondosComponent,
    FormasPagoComponent,
    DestinosComponent,
    CategoriasSIBComponent,
    EstatusGarantiaRealComponent,
    EstatusAvaluosComponent,
    IngenierosValuadoresComponent,
    NotariosComponent,
    MotivosAjustesComponent,
    DiasInhabilesComponent,
    CobrosAdicionalesComponent,
    InstitucionesCobrosAdicionalesComponent,
    MotivosReservasComponent,
    DailogAgregarMotivosReservasComponent,
    DailogActualizarMotivosReservasComponent,
    DailogEliminarMotivosReservasComponent,
    DailogValorCobroComponent,
    DailogAgregarValorCobroComponent,
    DailogEliminarValorCobroComponent,
    FormasDesembolsoComponent,
    MotivosReferenciasClientesComponent,
    RelacionTransaccionDepositosComponent,
    MediosContactoComponent,
    CanalesVentaComponent,
    TiposCanalesDistribucionComponent,
    AcercamientosComponent,
    AsesoresPrestamoComponent,
    BancosComponent,
    TiposDeduccionesComponent,
    TiposPrestamosComponent,
    ArchivosLimpiezaComponent,
    FrecuenciasAmortizacionComponent,
    GarantiasContablesComponent,    
    ParametrizacionNumeroPrestamoComponent,
    PasosCierreComponent,
    TiposTransaccionesComponent,
    MontosPlazoComponent,
    DatosGeneralesComponet,
    DialogG,
    DialogE,
    DialogN,
    DialogA,
    TiposSubtiposGarantiasRealesComponent,
    EstadosPrestamosComponent,
    LimpiezaArchivosComponent,
    ConsultasComponent,
    ProductosComponent,
    ClasificacionComponent,
    ParametrosAdicionalesProductosComponent,
    EventosSolicitudesComponent,
    DocumentosProductoComponent,
    PorcentajeFinanciamientoComponent,
    RangoPlazoInteresComponent,
    DefinirCategoriaUsuarioComponent,
    AsignacionCategoriasComponent,
    CopiarParametrosProductosComponent,
    Estatuslegalescomponent,
    DailogAgregarCategoriaSIB,
    DailogEliminarCategoriaSIB,
    DailogEditarCategoriaSIB,
    DailogAgregarEstatusGarantiaReal,
    DailogEditarEstatusGarantiaReal,
    DailogEliminarEstatusGarantiaReal,
    DailogAgregarEstatusAvaluos,
    DailogEditarEstatusAvaluos,
    DailogEliminarEstatusAvaluos,
    DailogAgregarIngenierosValuadores,
    DailogEditarIngenierosValuadores,
    DailogEliminarIngenierosValuadores,
    DialogOverviewExampleDialog,
    CrearAcercamiento,
    CrearAsesoresPrestamos,
    DialogCanal,
    DialogEliminarCanal,
    DialogCobroAdicional,
    DialogDestinos,
    DialogDiaInhabil,
    DialogFormas,
    DialogAgregarMotivoAjuste,
    DialogActualizarMotivoAjuste,
    DialogEliminarMotivoAjuste,
    DialogNotario,
    DialogRelacion,
    DialogEliminarRelacion,
    DialogTiposC,
    CrearTiposDeducciones,
    DialogOrigen,
    DialogContacto,
    DialogEliminarContacto,
    DailogAgregarCategoriaUsuario,
    DailogEliminarCategoriaUsuario,
    DailogEditarCategoriaUsuario,
    DialogTp,
    DialogTr,
    DialogGa,
    DialogTiposSubtiposAgregar,
    DialogTiposSubtiposAgregarCheck,
    TiposSubtiposGarantiasCheckAgregar,
    DialogFrecuenciaAmortizacionAgregar,
    DialogParaPrestamoAgregar,
    DialogEventoPasos,
    DialogLimpieza,
    DialogEliminarArchivosLimpieza,
    DialogArchivos,
    CrearProducto,
    EditarProducto,
    EliminarProducto,
    DialogConsultas,
    DialogClasificacion,
    DialogEvento,
    DialogDocumentoProducto,
    DialogAsignacionCategorias,
    DialogEliminarAsignacionCategorias,
    DialogAsignacionCategoriasV,
    DialogAsignacionCategoriasT,
    DialogEliminarAsignacionTipoProducto,
    dialogCopiarParametros,
    dialogEstatusLegales,
    CrearBancos,
    SidenavComponent,
    DialogDesembolsoAgregar,
    DialogCobrosAgregar,
    DialogCobrosAgregarCheck,
    DailogAgregarEstadoPrestamo,
    DailogActualizarEstadoPrestamo,
    DailogEliminarEstadoPrestamo,
    DailogSubEstadoPrestamo,
    DailogAgregarSubEstadoPrestamo,
    DailogActualizarSubEstadoPrestamo,
    DailogEliminarSubEstadoPrestamo,
    DailogTrasladoEstadoPrestamo,
    DailogAgregarTrasladoEstadoPrestamo,
    DailogActualizarTrasladoEstadoPrestamo,
    DailogEliminarTrasladoEstadoPrestamo,
    DailogCriteriosTraslado,
    DailogAgregarCriterio,
    DailogActualizarCriterio,
    DailogEliminarCriterio,
    EnlaceContabilidadComponent,
    DailogAgregarEnlaceContabilidad,
    DailogEliminarEnlaceContabilidad,
    DailogEditarEnlaceContabilidad,
    NivelesContabilizacionComponent,
    DailogAgregarNivelesContabilizacion,
    DailogEliminarNivelesContabilizacion,
    ContenidosContablesComponent,
    DailogAgregarContenidosContables,
    DailogEditarContenidosContables,
    DailogEliminarContenidosContables,
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    MetarialModule,
    AppRoutingModule,
    FormsModule,
    MatRippleModule,
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  entryComponents: [
    DialogAlma,
    DialogActualizarAlma,
    DialogEliminarAlma,    
    DialogAseg,
    DialogActualizarAseg,
    DialogEliminarAseg,
    DailogAgregarCategoriaSIB,
    DailogEditarCategoriaSIB,  
    DailogEliminarCategoriaSIB,
    DailogAgregarEstatusGarantiaReal,
    DailogEditarEstatusGarantiaReal,
    DailogEliminarEstatusGarantiaReal,
    DailogAgregarEstatusAvaluos,
    DailogEditarEstatusAvaluos,
    DailogEliminarEstatusAvaluos,
    DailogAgregarIngenierosValuadores,
    DailogEditarIngenierosValuadores,
    DailogEliminarIngenierosValuadores,
    DialogOverviewExampleDialog,
    CrearAcercamiento,
    CrearAsesoresPrestamos,
    DialogCanal,
    DialogEliminarCanal,
    DialogCobroAdicional,
    DialogDestinos,
    DialogDiaInhabil,
    DialogFormas,
    DialogAgregarMotivoAjuste,
    DialogActualizarMotivoAjuste,
    DialogEliminarMotivoAjuste,
    DialogNotario,
    DialogRelacion,
    DialogEliminarRelacion,
    DialogTiposC,
    CrearTiposDeducciones,
    DialogOrigen,
    DialogContacto,
    DialogEliminarContacto,
    DailogAgregarCategoriaUsuario,
    DailogEliminarCategoriaUsuario,
    DailogEditarCategoriaUsuario,
    DialogTp,
    DialogTr,
    DialogGa,
    DialogTiposSubtiposAgregar,
    DialogTiposSubtiposAgregarCheck,
    TiposSubtiposGarantiasCheckAgregar,
    DialogFrecuenciaAmortizacionAgregar,
    DialogParaPrestamoAgregar,
    DialogEventoPasos,
    DialogLimpieza,
    DialogEliminarArchivosLimpieza,
    DialogArchivos,
    CrearProducto,
    EditarProducto,
    EliminarProducto,
    DialogConsultas,
    DialogClasificacion,
    DialogEvento,
    DialogDocumentoProducto,
    DialogAsignacionCategorias,
    DialogAsignacionCategorias,
    DialogEliminarAsignacionCategorias,
    DialogAsignacionCategoriasV,
    DialogAsignacionCategoriasT,
    DialogEliminarAsignacionTipoProducto,
    dialogCopiarParametros,
    dialogEstatusLegales,
    CrearBancos,
    DialogDesembolsoAgregar,
    DialogCobrosAgregar,
    DialogCobrosAgregarCheck,
    DailogAgregarEstadoPrestamo,
    DailogActualizarEstadoPrestamo,
    DailogEliminarEstadoPrestamo,
    DailogSubEstadoPrestamo,
    DailogAgregarSubEstadoPrestamo,
    DailogActualizarSubEstadoPrestamo,
    DailogEliminarSubEstadoPrestamo,
    DailogTrasladoEstadoPrestamo,
    DailogAgregarTrasladoEstadoPrestamo,
    DailogActualizarTrasladoEstadoPrestamo,
    DailogEliminarTrasladoEstadoPrestamo,
    DailogCriteriosTraslado,
    DailogAgregarCriterio,
    DailogActualizarCriterio,
    DailogEliminarCriterio,
    DialogG,
    DialogE,
    DialogN,
    DialogA,
    DailogAgregarEnlaceContabilidad,
    DailogEliminarEnlaceContabilidad,
    DailogEditarEnlaceContabilidad,
    DailogAgregarNivelesContabilizacion,
    DailogEliminarNivelesContabilizacion,
    DailogAgregarContenidosContables,
    DailogEditarContenidosContables,
    DailogEliminarContenidosContables,
    DailogAgregarMotivosReservasComponent,
    DailogActualizarMotivosReservasComponent,
    DailogEliminarMotivosReservasComponent,
    DailogValorCobroComponent,
    DailogAgregarValorCobroComponent,
    DailogEliminarValorCobroComponent,
    DialogAgregarlugaresInversion,
    DialogActualizarlugaresInversion,
    DialogEliminarlugaresInversion,

    HomeComponent
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
